### PR TITLE
Add test_project.xml

### PR DESCRIPTION
**Pull request by pbchase**
When I tested the last set of PRs I made a test project to address some of the complexity I had to test. It seems like something worth preserving.

### CODE REVIEW

**Comment by ChemiKyle** [comment]
Including data was a good idea, but unfortunately importing a project XML is a single event in `redcap_log_event`, so `@DEFAULT-FROM-PREVIOUS-EVENT` tags don't act as expected with chronological order.

**Comment by pbchase** [comment]
Do you you think we should ditch the data to prevent confusion?

**Comment by ChemiKyle** [comment]
It's still useful outside the context of chronological ordering; maybe some words in the README that explain a new record should be made and populated manually to test that feature.

**Comment by ChemiKyle** [comment]
Branching logic examples need to be added as well; coincidentally, that would make this project XML a nice platform to reproduce/test solutions for issue #32  
I will attempt to make an additional commit on this PR

**Pull request merged**
